project_id = "rgttklitvvqsnlsakvzr"

[functions.meta-oauth-callback]
verify_jwt = false

[functions.ads-telegram-webhook]
verify_jwt = false

[functions.greenapi-webhook]
verify_jwt = false

[functions.greenapi-sync-name]
verify_jwt = false
